version: "3.2"

services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpsite
    deploy:
      placement:
        constraints:
          - node.role == manager

  web:
    depends_on:
      - db
    # image: wordpress:5.6.2
    image: registry.ctf.secompufscar.com.br/wordpress-rev-shell:latest
    deploy:
      labels:
        - "traefik.enable=true"
        # change the host here
        - "traefik.http.routers.web.rule=Host(`web.ctf.secompufscar.com.br`)"
        - "traefik.http.services.web.loadbalancer.server.port=80"
        - "traefik.http.routers.web.entrypoints=websecure"
        - "traefik.http.routers.web.tls=true"
        - "traefik.http.routers.web.tls.certresolver=leresolver"
      resources:
        limits:
          cpus: "0.2"
          memory: 400M
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wpsite
      - traefik-public

volumes:
  db_data:

networks:
  wpsite:
    driver: overlay

  traefik-public:
    external: true
