version: "3.2"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-nosql
    deploy:
      placement:
        constraints:
          - node.role == manager

  app-nosql:
    build:
      context: .
    networks:
      - app-nosql
    ports:
      - 8080:5000

volumes:
  mongodb_data:

networks:
  app-nosql:
